In [3]:
import math

print(math.sqrt(16))

4.0


In [4]:
from math import sqrt

print(sqrt(25))

5.0


In [6]:
from math import sqrt, pow

print(sqrt(16))  # Output: 4.0
print(pow(2, 3))

4.0
8.0


In [7]:
import numpy as np

array = np.array([1, 2, 3])
print(array) 


[1 2 3]


In [8]:
from numpy import array
newarray = array([1,2,3,5])
print(newarray)

[1 2 3]


In [9]:
from numpy import array as ar

newarray = ar([1,2,3,5,8,9])
print(newarray)


[1 2 3 5 8 9]
